<?php
namespace HistoricalConquest;
define('CARD_LAND',0);
define('CARD_CHARACTER_ACTIVIST',1);
define('CARD_CHARACTER_ARTIST',2);
define('CARD_CHARACTER_ASSASSIN',3);
define('CARD_CHARACTER_ATHLETE',4);
define('CARD_CHARACTER_AUTHOR',5);
define('CARD_CHARACTER_BUSINESSMAN',6);
define('CARD_CHARACTER_CONQUEROR',7);
define('CARD_CHARACTER_ENTERTAINER',8);
define('CARD_CHARACTER_ECONOMIST',9);
define('CARD_CHARACTER_EXPLORER_SEA',10);
define('CARD_CHARACTER_EXPLORER_AIR',11);
define('CARD_CHARACTER_EXPLORER_LAND',12);
define('CARD_CHARACTER_EXPLORER_SPACE',13);
define('CARD_CHARACTER_INVENTOR',14);
define('CARD_CHARACTER_LAW_ENFORCEMENT',15);
define('CARD_CHARACTER_LEADER',16);
define('CARD_CHARACTER_MUSICIAN',17);
define('CARD_CHARACTER_OUTLAW_PIRATE',18);
define('CARD_CHARACTER_OUTLAW_MOBSTER',19);
define('CARD_CHARACTER_OUTLAW_REBEL',20);
define('CARD_CHARACTER_PHILOSOPHER',21);
define('CARD_CHARACTER_POLITICIAN',22);
define('CARD_CHARACTER_SCIENTIST',23);
define('CARD_CHARACTER_SPIRTUAL_LEADER',24);
define('CARD_CHARACTER_WARRIOR',25);
define('CARD_ARMY',26);
define('CARD_VESSEL',27);
define('CARD_EVENT',28);
define('CARD_KNOWLEDGE',29);
define('CARD_ORGANIZATION',30);
define('CARD_TECHNOLOGY',31);
define('CARD_LOCATION',32);
define('CARD_DOCUMENT',33);
define('SCOPE_ALWAYS_ON',34);
define('SCOPE_ANYTIME',35);
define('SCOPE_TURN',36);
define('SCOPE_ATTACK',37);
define('SCOPE_DEFENSE',38);
define('APPLY_PLAYER',39);
define('APPLY_OPPONENT',40);
define('APPLY_ALL_OPPONENTS',41);
define('APPLY_CARD_IN_SAME_COLUMN',42);
define('APPLY_CARD_PLAYED',43);
define('APPLY_CARDS_IN_COLUMN',44);
define('APPLY_CARDS_PLAYED',45);
define('APPLY_OPPONENT_CARD_IN_SAME_COLUMN',46);
define('APPLY_OPPONENT_CARD_PLAYED',47);
define('APPLY_OPPONENT_CARDS_IN_COLUMN',48);
define('APPLY_OPPONENT_CARDS_PLAYED',49);
define('USAGE_IMMEDIATE',50);
define('USAGE_HOLD',51);
define('USAGE_CONSTANT',52);
define('ABILITY_INTERRUPT',53);
define('ABILITY_CHOICE',54);
define('ABILITY_MULTI',55);
define('RELIGION_CHRISTIAN',56);
define('RELIGION_CATHOLIC',57);
define('RELIGION_ORTHODOX_CHRISTIAN',58);
define('RELIGION_PROTESTANT',59);
define('RELIGION_MUSLIM',60);
define('RELIGION_MUSLIM_SHIITE',61);
define('RELIGION_MUSLIM_SUNNI',62);
define('RELIGION_BUDDHIST',63);
define('RELIGION_HINDU',64);
define('RELIGION_ATHEIST',65);
define('RELIGION_JEWISH',66);
define('CONTINENT_NORTH_AMERICA',67);
define('CONTINENT_ASIA',68);
define('CONTINENT_EUROPE',69);
define('CONTINENT_AFRICA',70);
define('CONTINENT_SOUTH_AMERICA',71);
define('CONTINENT_ANTARCTICA',72);
define('CONTINENT_AUSTRALIA',73);
define('CLIMATE_TROPICAL',74);
define('CLIMATE_DRY',75);
define('CLIMATE_TEMPERATE',76);
define('CLIMATE_CONTINENTAL',77);
define('CLIMATE_POLAR',78);
function type_to_name($val) { 
	 if ( $val == CARD_LAND ) { return 'CARD_LAND'; }
	 if ( $val == CARD_CHARACTER_ACTIVIST ) { return 'CARD_CHARACTER_ACTIVIST'; }
	 if ( $val == CARD_CHARACTER_ARTIST ) { return 'CARD_CHARACTER_ARTIST'; }
	 if ( $val == CARD_CHARACTER_ASSASSIN ) { return 'CARD_CHARACTER_ASSASSIN'; }
	 if ( $val == CARD_CHARACTER_ATHLETE ) { return 'CARD_CHARACTER_ATHLETE'; }
	 if ( $val == CARD_CHARACTER_AUTHOR ) { return 'CARD_CHARACTER_AUTHOR'; }
	 if ( $val == CARD_CHARACTER_BUSINESSMAN ) { return 'CARD_CHARACTER_BUSINESSMAN'; }
	 if ( $val == CARD_CHARACTER_CONQUEROR ) { return 'CARD_CHARACTER_CONQUEROR'; }
	 if ( $val == CARD_CHARACTER_ENTERTAINER ) { return 'CARD_CHARACTER_ENTERTAINER'; }
	 if ( $val == CARD_CHARACTER_ECONOMIST ) { return 'CARD_CHARACTER_ECONOMIST'; }
	 if ( $val == CARD_CHARACTER_EXPLORER_SEA ) { return 'CARD_CHARACTER_EXPLORER_SEA'; }
	 if ( $val == CARD_CHARACTER_EXPLORER_AIR ) { return 'CARD_CHARACTER_EXPLORER_AIR'; }
	 if ( $val == CARD_CHARACTER_EXPLORER_LAND ) { return 'CARD_CHARACTER_EXPLORER_LAND'; }
	 if ( $val == CARD_CHARACTER_EXPLORER_SPACE ) { return 'CARD_CHARACTER_EXPLORER_SPACE'; }
	 if ( $val == CARD_CHARACTER_INVENTOR ) { return 'CARD_CHARACTER_INVENTOR'; }
	 if ( $val == CARD_CHARACTER_LAW_ENFORCEMENT ) { return 'CARD_CHARACTER_LAW_ENFORCEMENT'; }
	 if ( $val == CARD_CHARACTER_LEADER ) { return 'CARD_CHARACTER_LEADER'; }
	 if ( $val == CARD_CHARACTER_MUSICIAN ) { return 'CARD_CHARACTER_MUSICIAN'; }
	 if ( $val == CARD_CHARACTER_OUTLAW_PIRATE ) { return 'CARD_CHARACTER_OUTLAW_PIRATE'; }
	 if ( $val == CARD_CHARACTER_OUTLAW_MOBSTER ) { return 'CARD_CHARACTER_OUTLAW_MOBSTER'; }
	 if ( $val == CARD_CHARACTER_OUTLAW_REBEL ) { return 'CARD_CHARACTER_OUTLAW_REBEL'; }
	 if ( $val == CARD_CHARACTER_PHILOSOPHER ) { return 'CARD_CHARACTER_PHILOSOPHER'; }
	 if ( $val == CARD_CHARACTER_POLITICIAN ) { return 'CARD_CHARACTER_POLITICIAN'; }
	 if ( $val == CARD_CHARACTER_SCIENTIST ) { return 'CARD_CHARACTER_SCIENTIST'; }
	 if ( $val == CARD_CHARACTER_SPIRTUAL_LEADER ) { return 'CARD_CHARACTER_SPIRTUAL_LEADER'; }
	 if ( $val == CARD_CHARACTER_WARRIOR ) { return 'CARD_CHARACTER_WARRIOR'; }
	 if ( $val == CARD_ARMY ) { return 'CARD_ARMY'; }
	 if ( $val == CARD_VESSEL ) { return 'CARD_VESSEL'; }
	 if ( $val == CARD_EVENT ) { return 'CARD_EVENT'; }
	 if ( $val == CARD_KNOWLEDGE ) { return 'CARD_KNOWLEDGE'; }
	 if ( $val == CARD_ORGANIZATION ) { return 'CARD_ORGANIZATION'; }
	 if ( $val == CARD_TECHNOLOGY ) { return 'CARD_TECHNOLOGY'; }
	 if ( $val == CARD_LOCATION ) { return 'CARD_LOCATION'; }
	 if ( $val == CARD_DOCUMENT ) { return 'CARD_DOCUMENT'; }
	 if ( $val == SCOPE_ALWAYS_ON ) { return 'SCOPE_ALWAYS_ON'; }
	 if ( $val == SCOPE_ANYTIME ) { return 'SCOPE_ANYTIME'; }
	 if ( $val == SCOPE_TURN ) { return 'SCOPE_TURN'; }
	 if ( $val == SCOPE_ATTACK ) { return 'SCOPE_ATTACK'; }
	 if ( $val == SCOPE_DEFENSE ) { return 'SCOPE_DEFENSE'; }
	 if ( $val == APPLY_PLAYER ) { return 'APPLY_PLAYER'; }
	 if ( $val == APPLY_OPPONENT ) { return 'APPLY_OPPONENT'; }
	 if ( $val == APPLY_ALL_OPPONENTS ) { return 'APPLY_ALL_OPPONENTS'; }
	 if ( $val == APPLY_CARD_IN_SAME_COLUMN ) { return 'APPLY_CARD_IN_SAME_COLUMN'; }
	 if ( $val == APPLY_CARD_PLAYED ) { return 'APPLY_CARD_PLAYED'; }
	 if ( $val == APPLY_CARDS_IN_COLUMN ) { return 'APPLY_CARDS_IN_COLUMN'; }
	 if ( $val == APPLY_CARDS_PLAYED ) { return 'APPLY_CARDS_PLAYED'; }
	 if ( $val == APPLY_OPPONENT_CARD_IN_SAME_COLUMN ) { return 'APPLY_OPPONENT_CARD_IN_SAME_COLUMN'; }
	 if ( $val == APPLY_OPPONENT_CARD_PLAYED ) { return 'APPLY_OPPONENT_CARD_PLAYED'; }
	 if ( $val == APPLY_OPPONENT_CARDS_IN_COLUMN ) { return 'APPLY_OPPONENT_CARDS_IN_COLUMN'; }
	 if ( $val == APPLY_OPPONENT_CARDS_PLAYED ) { return 'APPLY_OPPONENT_CARDS_PLAYED'; }
	 if ( $val == USAGE_IMMEDIATE ) { return 'USAGE_IMMEDIATE'; }
	 if ( $val == USAGE_HOLD ) { return 'USAGE_HOLD'; }
	 if ( $val == USAGE_CONSTANT ) { return 'USAGE_CONSTANT'; }
	 if ( $val == ABILITY_INTERRUPT ) { return 'ABILITY_INTERRUPT'; }
	 if ( $val == ABILITY_CHOICE ) { return 'ABILITY_CHOICE'; }
	 if ( $val == ABILITY_MULTI ) { return 'ABILITY_MULTI'; }
	 if ( $val == RELIGION_CHRISTIAN ) { return 'RELIGION_CHRISTIAN'; }
	 if ( $val == RELIGION_CATHOLIC ) { return 'RELIGION_CATHOLIC'; }
	 if ( $val == RELIGION_ORTHODOX_CHRISTIAN ) { return 'RELIGION_ORTHODOX_CHRISTIAN'; }
	 if ( $val == RELIGION_PROTESTANT ) { return 'RELIGION_PROTESTANT'; }
	 if ( $val == RELIGION_MUSLIM ) { return 'RELIGION_MUSLIM'; }
	 if ( $val == RELIGION_MUSLIM_SHIITE ) { return 'RELIGION_MUSLIM_SHIITE'; }
	 if ( $val == RELIGION_MUSLIM_SUNNI ) { return 'RELIGION_MUSLIM_SUNNI'; }
	 if ( $val == RELIGION_BUDDHIST ) { return 'RELIGION_BUDDHIST'; }
	 if ( $val == RELIGION_HINDU ) { return 'RELIGION_HINDU'; }
	 if ( $val == RELIGION_ATHEIST ) { return 'RELIGION_ATHEIST'; }
	 if ( $val == RELIGION_JEWISH ) { return 'RELIGION_JEWISH'; }
	 if ( $val == CONTINENT_NORTH_AMERICA ) { return 'CONTINENT_NORTH_AMERICA'; }
	 if ( $val == CONTINENT_ASIA ) { return 'CONTINENT_ASIA'; }
	 if ( $val == CONTINENT_EUROPE ) { return 'CONTINENT_EUROPE'; }
	 if ( $val == CONTINENT_AFRICA ) { return 'CONTINENT_AFRICA'; }
	 if ( $val == CONTINENT_SOUTH_AMERICA ) { return 'CONTINENT_SOUTH_AMERICA'; }
	 if ( $val == CONTINENT_ANTARCTICA ) { return 'CONTINENT_ANTARCTICA'; }
	 if ( $val == CONTINENT_AUSTRALIA ) { return 'CONTINENT_AUSTRALIA'; }
	 if ( $val == CLIMATE_TROPICAL ) { return 'CLIMATE_TROPICAL'; }
	 if ( $val == CLIMATE_DRY ) { return 'CLIMATE_DRY'; }
	 if ( $val == CLIMATE_TEMPERATE ) { return 'CLIMATE_TEMPERATE'; }
	 if ( $val == CLIMATE_CONTINENTAL ) { return 'CLIMATE_CONTINENTAL'; }
	 if ( $val == CLIMATE_POLAR ) { return 'CLIMATE_POLAR'; }
}
function name_to_type($val) { 
	 if ( $val == 'CARD_LAND' ) { return CARD_LAND; }
	 if ( $val == 'CARD_CHARACTER_ACTIVIST' ) { return CARD_CHARACTER_ACTIVIST; }
	 if ( $val == 'CARD_CHARACTER_ARTIST' ) { return CARD_CHARACTER_ARTIST; }
	 if ( $val == 'CARD_CHARACTER_ASSASSIN' ) { return CARD_CHARACTER_ASSASSIN; }
	 if ( $val == 'CARD_CHARACTER_ATHLETE' ) { return CARD_CHARACTER_ATHLETE; }
	 if ( $val == 'CARD_CHARACTER_AUTHOR' ) { return CARD_CHARACTER_AUTHOR; }
	 if ( $val == 'CARD_CHARACTER_BUSINESSMAN' ) { return CARD_CHARACTER_BUSINESSMAN; }
	 if ( $val == 'CARD_CHARACTER_CONQUEROR' ) { return CARD_CHARACTER_CONQUEROR; }
	 if ( $val == 'CARD_CHARACTER_ENTERTAINER' ) { return CARD_CHARACTER_ENTERTAINER; }
	 if ( $val == 'CARD_CHARACTER_ECONOMIST' ) { return CARD_CHARACTER_ECONOMIST; }
	 if ( $val == 'CARD_CHARACTER_EXPLORER_SEA' ) { return CARD_CHARACTER_EXPLORER_SEA; }
	 if ( $val == 'CARD_CHARACTER_EXPLORER_AIR' ) { return CARD_CHARACTER_EXPLORER_AIR; }
	 if ( $val == 'CARD_CHARACTER_EXPLORER_LAND' ) { return CARD_CHARACTER_EXPLORER_LAND; }
	 if ( $val == 'CARD_CHARACTER_EXPLORER_SPACE' ) { return CARD_CHARACTER_EXPLORER_SPACE; }
	 if ( $val == 'CARD_CHARACTER_INVENTOR' ) { return CARD_CHARACTER_INVENTOR; }
	 if ( $val == 'CARD_CHARACTER_LAW_ENFORCEMENT' ) { return CARD_CHARACTER_LAW_ENFORCEMENT; }
	 if ( $val == 'CARD_CHARACTER_LEADER' ) { return CARD_CHARACTER_LEADER; }
	 if ( $val == 'CARD_CHARACTER_MUSICIAN' ) { return CARD_CHARACTER_MUSICIAN; }
	 if ( $val == 'CARD_CHARACTER_OUTLAW_PIRATE' ) { return CARD_CHARACTER_OUTLAW_PIRATE; }
	 if ( $val == 'CARD_CHARACTER_OUTLAW_MOBSTER' ) { return CARD_CHARACTER_OUTLAW_MOBSTER; }
	 if ( $val == 'CARD_CHARACTER_OUTLAW_REBEL' ) { return CARD_CHARACTER_OUTLAW_REBEL; }
	 if ( $val == 'CARD_CHARACTER_PHILOSOPHER' ) { return CARD_CHARACTER_PHILOSOPHER; }
	 if ( $val == 'CARD_CHARACTER_POLITICIAN' ) { return CARD_CHARACTER_POLITICIAN; }
	 if ( $val == 'CARD_CHARACTER_SCIENTIST' ) { return CARD_CHARACTER_SCIENTIST; }
	 if ( $val == 'CARD_CHARACTER_SPIRTUAL_LEADER' ) { return CARD_CHARACTER_SPIRTUAL_LEADER; }
	 if ( $val == 'CARD_CHARACTER_WARRIOR' ) { return CARD_CHARACTER_WARRIOR; }
	 if ( $val == 'CARD_ARMY' ) { return CARD_ARMY; }
	 if ( $val == 'CARD_VESSEL' ) { return CARD_VESSEL; }
	 if ( $val == 'CARD_EVENT' ) { return CARD_EVENT; }
	 if ( $val == 'CARD_KNOWLEDGE' ) { return CARD_KNOWLEDGE; }
	 if ( $val == 'CARD_ORGANIZATION' ) { return CARD_ORGANIZATION; }
	 if ( $val == 'CARD_TECHNOLOGY' ) { return CARD_TECHNOLOGY; }
	 if ( $val == 'CARD_LOCATION' ) { return CARD_LOCATION; }
	 if ( $val == 'CARD_DOCUMENT' ) { return CARD_DOCUMENT; }
	 if ( $val == 'SCOPE_ALWAYS_ON' ) { return SCOPE_ALWAYS_ON; }
	 if ( $val == 'SCOPE_ANYTIME' ) { return SCOPE_ANYTIME; }
	 if ( $val == 'SCOPE_TURN' ) { return SCOPE_TURN; }
	 if ( $val == 'SCOPE_ATTACK' ) { return SCOPE_ATTACK; }
	 if ( $val == 'SCOPE_DEFENSE' ) { return SCOPE_DEFENSE; }
	 if ( $val == 'APPLY_PLAYER' ) { return APPLY_PLAYER; }
	 if ( $val == 'APPLY_OPPONENT' ) { return APPLY_OPPONENT; }
	 if ( $val == 'APPLY_ALL_OPPONENTS' ) { return APPLY_ALL_OPPONENTS; }
	 if ( $val == 'APPLY_CARD_IN_SAME_COLUMN' ) { return APPLY_CARD_IN_SAME_COLUMN; }
	 if ( $val == 'APPLY_CARD_PLAYED' ) { return APPLY_CARD_PLAYED; }
	 if ( $val == 'APPLY_CARDS_IN_COLUMN' ) { return APPLY_CARDS_IN_COLUMN; }
	 if ( $val == 'APPLY_CARDS_PLAYED' ) { return APPLY_CARDS_PLAYED; }
	 if ( $val == 'APPLY_OPPONENT_CARD_IN_SAME_COLUMN' ) { return APPLY_OPPONENT_CARD_IN_SAME_COLUMN; }
	 if ( $val == 'APPLY_OPPONENT_CARD_PLAYED' ) { return APPLY_OPPONENT_CARD_PLAYED; }
	 if ( $val == 'APPLY_OPPONENT_CARDS_IN_COLUMN' ) { return APPLY_OPPONENT_CARDS_IN_COLUMN; }
	 if ( $val == 'APPLY_OPPONENT_CARDS_PLAYED' ) { return APPLY_OPPONENT_CARDS_PLAYED; }
	 if ( $val == 'USAGE_IMMEDIATE' ) { return USAGE_IMMEDIATE; }
	 if ( $val == 'USAGE_HOLD' ) { return USAGE_HOLD; }
	 if ( $val == 'USAGE_CONSTANT' ) { return USAGE_CONSTANT; }
	 if ( $val == 'ABILITY_INTERRUPT' ) { return ABILITY_INTERRUPT; }
	 if ( $val == 'ABILITY_CHOICE' ) { return ABILITY_CHOICE; }
	 if ( $val == 'ABILITY_MULTI' ) { return ABILITY_MULTI; }
	 if ( $val == 'RELIGION_CHRISTIAN' ) { return RELIGION_CHRISTIAN; }
	 if ( $val == 'RELIGION_CATHOLIC' ) { return RELIGION_CATHOLIC; }
	 if ( $val == 'RELIGION_ORTHODOX_CHRISTIAN' ) { return RELIGION_ORTHODOX_CHRISTIAN; }
	 if ( $val == 'RELIGION_PROTESTANT' ) { return RELIGION_PROTESTANT; }
	 if ( $val == 'RELIGION_MUSLIM' ) { return RELIGION_MUSLIM; }
	 if ( $val == 'RELIGION_MUSLIM_SHIITE' ) { return RELIGION_MUSLIM_SHIITE; }
	 if ( $val == 'RELIGION_MUSLIM_SUNNI' ) { return RELIGION_MUSLIM_SUNNI; }
	 if ( $val == 'RELIGION_BUDDHIST' ) { return RELIGION_BUDDHIST; }
	 if ( $val == 'RELIGION_HINDU' ) { return RELIGION_HINDU; }
	 if ( $val == 'RELIGION_ATHEIST' ) { return RELIGION_ATHEIST; }
	 if ( $val == 'RELIGION_JEWISH' ) { return RELIGION_JEWISH; }
	 if ( $val == 'CONTINENT_NORTH_AMERICA' ) { return CONTINENT_NORTH_AMERICA; }
	 if ( $val == 'CONTINENT_ASIA' ) { return CONTINENT_ASIA; }
	 if ( $val == 'CONTINENT_EUROPE' ) { return CONTINENT_EUROPE; }
	 if ( $val == 'CONTINENT_AFRICA' ) { return CONTINENT_AFRICA; }
	 if ( $val == 'CONTINENT_SOUTH_AMERICA' ) { return CONTINENT_SOUTH_AMERICA; }
	 if ( $val == 'CONTINENT_ANTARCTICA' ) { return CONTINENT_ANTARCTICA; }
	 if ( $val == 'CONTINENT_AUSTRALIA' ) { return CONTINENT_AUSTRALIA; }
	 if ( $val == 'CLIMATE_TROPICAL' ) { return CLIMATE_TROPICAL; }
	 if ( $val == 'CLIMATE_DRY' ) { return CLIMATE_DRY; }
	 if ( $val == 'CLIMATE_TEMPERATE' ) { return CLIMATE_TEMPERATE; }
	 if ( $val == 'CLIMATE_CONTINENTAL' ) { return CLIMATE_CONTINENTAL; }
	 if ( $val == 'CLIMATE_POLAR' ) { return CLIMATE_POLAR; }
}
function options_by_prefix($pref) { 
	 $defs = array (
  'CARD' => 
  array (
    0 => 'CARD_LAND',
    1 => 'CARD_CHARACTER_ACTIVIST',
    2 => 'CARD_CHARACTER_ARTIST',
    3 => 'CARD_CHARACTER_ASSASSIN',
    4 => 'CARD_CHARACTER_ATHLETE',
    5 => 'CARD_CHARACTER_AUTHOR',
    6 => 'CARD_CHARACTER_BUSINESSMAN',
    7 => 'CARD_CHARACTER_CONQUEROR',
    8 => 'CARD_CHARACTER_ENTERTAINER',
    9 => 'CARD_CHARACTER_ECONOMIST',
    10 => 'CARD_CHARACTER_EXPLORER_SEA',
    11 => 'CARD_CHARACTER_EXPLORER_AIR',
    12 => 'CARD_CHARACTER_EXPLORER_LAND',
    13 => 'CARD_CHARACTER_EXPLORER_SPACE',
    14 => 'CARD_CHARACTER_INVENTOR',
    15 => 'CARD_CHARACTER_LAW_ENFORCEMENT',
    16 => 'CARD_CHARACTER_LEADER',
    17 => 'CARD_CHARACTER_MUSICIAN',
    18 => 'CARD_CHARACTER_OUTLAW_PIRATE',
    19 => 'CARD_CHARACTER_OUTLAW_MOBSTER',
    20 => 'CARD_CHARACTER_OUTLAW_REBEL',
    21 => 'CARD_CHARACTER_PHILOSOPHER',
    22 => 'CARD_CHARACTER_POLITICIAN',
    23 => 'CARD_CHARACTER_SCIENTIST',
    24 => 'CARD_CHARACTER_SPIRTUAL_LEADER',
    25 => 'CARD_CHARACTER_WARRIOR',
    26 => 'CARD_ARMY',
    27 => 'CARD_VESSEL',
    28 => 'CARD_EVENT',
    29 => 'CARD_KNOWLEDGE',
    30 => 'CARD_ORGANIZATION',
    31 => 'CARD_TECHNOLOGY',
    32 => 'CARD_LOCATION',
    33 => 'CARD_DOCUMENT',
  ),
  'SCOPE' => 
  array (
    0 => 'SCOPE_ALWAYS_ON',
    1 => 'SCOPE_ANYTIME',
    2 => 'SCOPE_TURN',
    3 => 'SCOPE_ATTACK',
    4 => 'SCOPE_DEFENSE',
  ),
  'APPLY' => 
  array (
    0 => 'APPLY_PLAYER',
    1 => 'APPLY_OPPONENT',
    2 => 'APPLY_ALL_OPPONENTS',
    3 => 'APPLY_CARD_IN_SAME_COLUMN',
    4 => 'APPLY_CARD_PLAYED',
    5 => 'APPLY_CARDS_IN_COLUMN',
    6 => 'APPLY_CARDS_PLAYED',
    7 => 'APPLY_OPPONENT_CARD_IN_SAME_COLUMN',
    8 => 'APPLY_OPPONENT_CARD_PLAYED',
    9 => 'APPLY_OPPONENT_CARDS_IN_COLUMN',
    10 => 'APPLY_OPPONENT_CARDS_PLAYED',
  ),
  'USAGE' => 
  array (
    0 => 'USAGE_IMMEDIATE',
    1 => 'USAGE_HOLD',
    2 => 'USAGE_CONSTANT',
  ),
  'ABILITY' => 
  array (
    0 => 'ABILITY_INTERRUPT',
    1 => 'ABILITY_CHOICE',
    2 => 'ABILITY_MULTI',
  ),
  'RELIGION' => 
  array (
    0 => 'RELIGION_CHRISTIAN',
    1 => 'RELIGION_CATHOLIC',
    2 => 'RELIGION_ORTHODOX_CHRISTIAN',
    3 => 'RELIGION_PROTESTANT',
    4 => 'RELIGION_MUSLIM',
    5 => 'RELIGION_MUSLIM_SHIITE',
    6 => 'RELIGION_MUSLIM_SUNNI',
    7 => 'RELIGION_BUDDHIST',
    8 => 'RELIGION_HINDU',
    9 => 'RELIGION_ATHEIST',
    10 => 'RELIGION_JEWISH',
  ),
  'CONTINENT' => 
  array (
    0 => 'CONTINENT_NORTH_AMERICA',
    1 => 'CONTINENT_ASIA',
    2 => 'CONTINENT_EUROPE',
    3 => 'CONTINENT_AFRICA',
    4 => 'CONTINENT_SOUTH_AMERICA',
    5 => 'CONTINENT_ANTARCTICA',
    6 => 'CONTINENT_AUSTRALIA',
  ),
  'CLIMATE' => 
  array (
    0 => 'CLIMATE_TROPICAL',
    1 => 'CLIMATE_DRY',
    2 => 'CLIMATE_TEMPERATE',
    3 => 'CLIMATE_CONTINENTAL',
    4 => 'CLIMATE_POLAR',
  ),
);

 return $defs[$pref];
}
