CREATE TABLE `hc_cards` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`deck` VARCHAR(16) NOT NULL DEFAULT '0',
	`name` VARCHAR(255) NOT NULL DEFAULT '0',
	`background_image` VARCHAR(255) NOT NULL DEFAULT '0',
	`background_color` VARCHAR(255) NOT NULL DEFAULT 'white',
	`border_color` VARCHAR(255) NOT NULL DEFAULT 'none',
	`text_color` VARCHAR(255) NOT NULL DEFAULT 'black',
	`illustration` VARCHAR(255) NOT NULL DEFAULT '0',
	`reference` VARCHAR(255) NOT NULL DEFAULT '0',
	`reference2` VARCHAR(255) NOT NULL DEFAULT '0',
	`gender` VARCHAR(12) NOT NULL DEFAULT 'male',
	`ext_id` VARCHAR(32) NOT NULL DEFAULT '0',
	`year` VARCHAR(32) NOT NULL DEFAULT '0',
	`maintype` TINYINT NOT NULL DEFAULT '0',
	`continent` TINYINT NOT NULL DEFAULT '0',
	`climate` TINYINT NOT NULL DEFAULT '0',
	`subtype1` TINYINT NOT NULL DEFAULT '0',
	`subtype2` TINYINT NOT NULL DEFAULT '0',
	`subtype3` TINYINT NOT NULL DEFAULT '0',
	`strength` INT NOT NULL DEFAULT '0',
	`defense` INT NOT NULL DEFAULT '0',
	`when_to_play` VARCHAR(32) NOT NULL DEFAULT '0',
	`summary` TEXT NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`),
	INDEX `maintype` (`maintype`, `subtype1`, `subtype2`, `subtype3`)
);
CREATE TABLE `hc_card_abilities` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`card_id` INT NOT NULL DEFAULT '0',
	`apply_to_type` TINYINT NOT NULL DEFAULT 0,
	`apply_to_scope` TINYINT NOT NULL DEFAULT 0,
	`affects_attribute` VARCHAR(50) NOT NULL DEFAULT '0',
	`affect_amount` INT NOT NULL DEFAULT 0,
	`apply_to_ext_ids` TEXT NOT NULL DEFAULT '0',
	`apply_to_card_types` TEXT NOT NULL DEFAULT '0',
	`ext_ids_present_in_colum` TEXT NOT NULL DEFAULT '0',
	`custom_function` TEXT NOT NULL DEFAULT '0',
	`named_function` VARCHAR(50) NOT NULL DEFAULT '0',
	`charges` TINYTEXT NOT NULL DEFAULT '0',
	`description` VARCHAR(255) NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`),
	INDEX `card_id` (`card_id`)
);
